from __future__ import annotations
from collections.abc import Callable, Iterator
from datetime import datetime
from typing import Protocol, runtime_checkable
from git_gui.domain.entities import Branch, Commit, CommitStat, FileStatus, Hunk, LocalBranchInfo, MergeAnalysisResult, MergeStrategy, Remote, RepoStateInfo, ResetMode, Stash, Submodule, Tag


@runtime_checkable
class IRepositoryReader(Protocol):
    def get_commits(
        self,
        limit: int,
        skip: int = 0,
        extra_tips: list[str] | None = None,
        *,
        first_parent: bool = False,
    ) -> list[Commit]: ...
    def get_commit(self, oid: str) -> Commit: ...
    def get_branches(self) -> list[Branch]: ...
    def get_stashes(self) -> list[Stash]: ...
    def get_commit_files(self, oid: str) -> list[FileStatus]: ...
    def get_file_diff(self, oid: str, path: str) -> list[Hunk]: ...
    def get_commit_diff_map(self, oid: str) -> dict[str, list[Hunk]]: ...
    def get_working_tree_diff_map(self) -> dict[str, dict[str, list[Hunk]]]: ...
    def get_staged_diff(self, path: str) -> list[Hunk]: ...
    def get_working_tree(self) -> list[FileStatus]: ...
    def is_dirty(self) -> bool: ...
    def get_head_oid(self) -> str | None: ...
    def get_tags(self) -> list[Tag]: ...
    def get_remote_tags(self, remote: str) -> list[str]: ...
    def list_remotes(self) -> list[Remote]: ...
    def list_submodules(self) -> list[Submodule]: ...
    def list_local_branches_with_upstream(self) -> list[LocalBranchInfo]: ...
    def get_commit_stats(
        self,
        since: datetime | None = None,
        until: datetime | None = None,
        *,
        cancel: Callable[[], bool] | None = None,
    ) -> Iterator[CommitStat]: ...
    def repo_state(self) -> RepoStateInfo: ...
    def is_ancestor(self, ancestor_oid: str, descendant_oid: str) -> bool: ...
    def merge_analysis(self, oid: str) -> MergeAnalysisResult: ...
    def get_merge_head(self) -> str | None: ...
    def get_merge_msg(self) -> str | None: ...
    def has_unresolved_conflicts(self) -> bool: ...
    def get_commit_range(self, head_oid: str, base_oid: str) -> list[Commit]: ...
    def merge_base(self, oid_a: str, oid_b: str) -> str | None: ...
    def get_identity(self) -> tuple[str | None, str | None]: ...
    """Return (user.name, user.email) from repo config; either may be None if unset."""


@runtime_checkable
class IRepositoryWriter(Protocol):
    def stage(self, paths: list[str]) -> None: ...
    def unstage(self, paths: list[str]) -> None: ...
    def stage_hunk(self, path: str, hunk_header: str) -> None: ...
    def unstage_hunk(self, path: str, hunk_header: str) -> None: ...
    def discard_file(self, path: str) -> None: ...
    def discard_hunk(self, path: str, hunk_header: str) -> None: ...
    def commit(self, message: str) -> Commit: ...
    def checkout(self, branch: str) -> None: ...
    def checkout_commit(self, oid: str) -> None: ...
    def checkout_remote_branch(self, remote_branch: str) -> None: ...
    def create_branch(self, name: str, from_oid: str) -> Branch: ...
    def delete_branch(self, name: str) -> None: ...
    def merge(self, branch: str, strategy: MergeStrategy = MergeStrategy.ALLOW_FF, message: str | None = None) -> None: ...
    def rebase(self, branch: str) -> None: ...
    def merge_commit(self, oid: str, strategy: MergeStrategy = MergeStrategy.ALLOW_FF, message: str | None = None) -> None: ...
    def rebase_onto_commit(self, oid: str) -> None: ...
    def push(self, remote: str, branch: str) -> None: ...
    def force_push(self, remote: str, branch: str) -> None: ...
    def pull(self, remote: str, branch: str) -> None: ...
    def fetch(self, remote: str) -> None: ...
    def fetch_all_prune(self) -> None: ...
    def stash(self, message: str) -> None: ...
    def pop_stash(self, index: int) -> None: ...
    def apply_stash(self, index: int) -> None: ...
    def drop_stash(self, index: int) -> None: ...
    def create_tag(self, name: str, oid: str, message: str | None = None) -> None: ...
    def delete_tag(self, name: str) -> None: ...
    def push_tag(self, remote: str, name: str) -> None: ...
    def delete_remote_branch(self, remote: str, branch: str) -> None: ...
    def delete_remote_tag(self, remote: str, name: str) -> None: ...
    def add_remote(self, name: str, url: str) -> None: ...
    def remove_remote(self, name: str) -> None: ...
    def rename_remote(self, old_name: str, new_name: str) -> None: ...
    def set_remote_url(self, name: str, url: str) -> None: ...
    def add_submodule(self, path: str, url: str) -> None: ...
    def remove_submodule(self, path: str) -> None: ...
    def set_submodule_url(self, path: str, url: str) -> None: ...
    def set_branch_upstream(self, name: str, upstream: str) -> None: ...
    def unset_branch_upstream(self, name: str) -> None: ...
    def rename_branch(self, old_name: str, new_name: str) -> None: ...
    def reset_branch_to_ref(self, branch: str, ref: str) -> None: ...
    def merge_abort(self) -> None: ...
    def rebase_abort(self) -> None: ...
    def rebase_continue(self, message: str = "") -> None: ...
    def interactive_rebase(self, target_oid: str, entries: list[tuple[str, str]]) -> None: ...
    def cherry_pick(self, oid: str) -> None: ...
    def revert_commit(self, oid: str) -> None: ...
    def reset_to(self, oid: str, mode: ResetMode) -> None: ...
    def cherry_pick_abort(self) -> None: ...
    def cherry_pick_continue(self) -> None: ...
    def revert_abort(self) -> None: ...
    def revert_continue(self) -> None: ...
    def set_identity(self, name: str, email: str, global_: bool) -> None: ...
    """Persist user.name and user.email via `git config [--global|--local]`."""


@runtime_checkable
class IRepoStore(Protocol):
    def load(self) -> None: ...
    def save(self) -> None: ...
    def get_open_repos(self) -> list[str]: ...
    def get_recent_repos(self) -> list[str]: ...
    def get_active(self) -> str | None: ...
    def add_open(self, path: str) -> None: ...
    def close_repo(self, path: str) -> None: ...
    def remove_recent(self, path: str) -> None: ...
    def set_active(self, path: str) -> None: ...
    def set_open_order(self, paths: list[str]) -> None: ...


@runtime_checkable
class IRemoteTagCache(Protocol):
    def load(self, repo_path: str) -> dict[str, list[str]]: ...
    def save(self, repo_path: str, data: dict[str, list[str]]) -> None: ...
